import type { Metadata } from "next";
import { Comic_Neue, Orbitron, Bangers } from "next/font/google";
import "./globals.css";
import { Header } from "@/shared/components/shared/Header";
import { Provider } from "@/shared/api/provider";

const ComicNeue = Comic_Neue({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
  variable: "--font-comic-neue",
});

const Orbit = Orbitron({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-orbitron",
});

const Banger = Bangers({
  weight: ["400"],
  subsets: ["latin", "latin-ext"],
  variable: "--font-banger",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider>
              <body className={`${Banger.className} antialiased comi`}>
        <Header />
        {children}
        <footer className="footer sm:footer-horizontal footer-center bg-base-300 text-base-content p-4">
          <aside>
            <p>
              Copyright © {new Date().getFullYear()} - All right reserved by
              Fanatic033 Industries Ltd
            </p>
          </aside>
        </footer>
      </body>
      </Provider>
    </html>
  );
}
// ${ComicNeue.className}  ${Orbit.className}
